// eslint-disable-next-line import/prefer-default-export
export enum FONT_SIZES {
  LARGE_HEADER = 38,
  MEDIUM_HEADER = 32,
  SMALL_HEADER = 28,
  LARGE_TEXT = 24,
  MEDIUM_TEXT = 16,
  MEDIUM_TEXT_ALTERNATIVE = 18,
  MEDIUM_LARGE_TEXT = 20,
  SMALL_TEXT = 13,
  SMALLER_TEXT = 12,
  SMALLEST_TEXT = 10,
  SMALL_TEXT_ALTERNATE = 14,
}
